      ******************************************************************
      * Created: Thu, 8 Feb 2024 10:46:30 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: TCSCUSCR
      * Workbook id: fdac967d-74ab-4c46-8463-7e4d36fa5040
      * Project: $clientCOBOL_7e7d74a4-039f-47cb-b59e-e8310079a4a6
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCSCUSCR.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
      ******************************************************************
      *  COPY SQLCA.
      * PATH : .../Cobol Include/SQLCA
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      * 01 SQLCA.
      *     05 SQLCODE     PIC S9(9) COMP-5.
      ******************************************************************
       COPY CUSTCONS.
      * PATH : .../Cobol Include/CUSTCONS.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01  CUSTOMER-CONSTANTS.
      *    10 CUSTOMER-OPERFAIL   PIC 99 VALUE 0.
      *    10 CUSTOMER-OPERSUCC   PIC 99 VALUE 3.
      ******************************************************************
      * PATH : .../zOS Cobol/TCSCUSCR.cbl
       01  CUSTOMER.
      ******************************************************************
           COPY CUSTCPY.
      * PATH : .../Cobol Include/CUSTCPY.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *    10 CUSTOMER-ID                PIC 9(9).
      *    10 CUSTOMER-NAME              PIC X(60).
      *    10 CUSTOMER-ADDRESS           PIC X(250).
      *    10 CUSTOMER-AGE               PIC 999.
      *    10 CUSTOMER-STATUS            PIC X.
      ******************************************************************
      * PATH : .../zOS Cobol/TCSCUSCR.cbl
       01 CUST-RETURN-CODE             PIC 99.
       01  CUSTOMER-COPY.
      ******************************************************************
           COPY LCUST.
      * PATH : .../Cobol Include/LCUST.cpy
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *    10 L-CUSTOMER-ID              PIC S9(9) USAGE COMP.
      ******************************************************************

      * SQLCA DB2 communications area
           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

           EXEC SQL
             INCLUDE CUSTOMER
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:TCSCUSCR
      * PROGRAM PATH : .../zOS Cobol/TCSCUSCR.cbl
      * STMT START LINE NUMBER : 220
      * STMT END LINE NUMBER : 244
       INSERT-NEW-CUSTOMER.
           EXEC SQL
             INSERT INTO
                    CUSTOMER
                    ( CUID ,
                      CUSTNAME ,
                      ADDRESS1 ,
                      AGE ,
                      STATUS1 )
             VALUES
                    ( :CUSTOMER-ID ,
                      :CUSTOMER-NAME ,
                      :CUSTOMER-ADDRESS ,
                      :CUSTOMER-AGE ,
                      :CUSTOMER-STATUS )
           END-EXEC.
           IF SQLCODE NOT = 0
              MOVE CUSTOMER-OPERFAIL TO CUST-RETURN-CODE
              DISPLAY '(TCSCUSCR) INSERT OPERATON FAILED.'
               ' SQLCODE=' SQLCODE
           ELSE
              MOVE CUSTOMER-OPERSUCC TO CUST-RETURN-CODE
              MOVE CUSTOMER-ID TO L-CUSTOMER-ID
              DISPLAY '(TCSCUSCR) CUSTOMER ADDED TO DATABASE.'
           END-IF.
      ******************************************************************
           EXIT PROGRAM.
